apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mon-pipeline
spec:
  workspaces:
    - name: source
  params:
    - name: build-image
      type: string
    - name: app-name
      type: string
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: source

    - name: test
      runAfter: [cleanup]
      taskRef:
        name: nose
      params:
        - name: args
          value: "-v"
      workspaces:
        - name: source
          workspace: source

    - name: deploy
      runAfter: [test]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
